services:
  app:
    image: ${IMAGE_NAME:-ghcr.io/abdulaziz27/xpresspos-backend:latest}
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "${APP_PORT:-8083}:8080"
    volumes:
      - storage:/var/www/html/storage
      - logs:/var/www/html/storage/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8080/healthz"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: "1.5"
          memory: 1024M
        reservations:
          cpus: "0.25"
          memory: 512M

  mysql:
    image: mysql:8.0
    container_name: xpresspos-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-xpresspos_prod}
      MYSQL_USER: ${DB_USERNAME:-xpresspos_prod}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root}
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-p${DB_ROOT_PASSWORD:-root}"]
      interval: 10s
      timeout: 5s
      retries: 6

volumes:
  storage:
  logs:
  db-data:
